version: "3.7"
services:
  python:
    build:
      dockerfile: Dockerfile
      context: ./
      args:
        homedir: /home/jovyan
    image: hirota/bowi
    volumes:
      - "${PWD}:/home/jovyan/bowi"
      - "${PWD}/bowi:/home/jovyan/.pyenv/versions/3.8.0/lib/python3.8/site-packages/bowi:ro"
    networks:
      - bowi_default
    environment:
      - HOME=/home/jovyan
      - PROJECT_ROOT=/home/jovyan/bowi
    env_file:
      - .env
    working_dir: /home/jovyan/bowi

  actions:
    image: hirota/bowi
    networks:
      - bowi_default
    volumes:
      - "${GITHUB_WORKSPACE}:/workplace"
      - "${GITHUB_WORKSPACE}/bowi:/usr/local/lib/python3.8/site-packages/bowi:ro"
    environment:
      - ES_URL=localhost  # dummy
      - PROJECT_ROOT=/workplace
    working_dir: /workplace

  lsp:
    build:
      dockerfile: Dockerfile.lsp
      context: ./
      args:
        NEW_USER: ${USER}
    image: hirota/lsp-bowi
    volumes:
      - "/home/${USER}/bowi:/home/${USER}/bowi"
      - "/home/${USER}/bowi/bowi:/home/jovyan/.pyenv/versions/3.8.0/lib/python3.8/site-packages/bowi:ro"
    ports:
      - 11001:11001
    stdin_open: true
    working_dir: "/home/${USER}/bowi"


networks:
  bowi_default:
    external: true
