version: "3.7"
services:
  python:
    build:
      dockerfile: Dockerfile
      context: ./
    image: hirota/bowi
    volumes:
      - "${HOME}/bowi:/home/jovyan/bowi"
      - "${HOME}/bowi/bowi:/usr/local/lib/python3.8/site-packages/bowi:ro"
    networks:
      - bowi_default
    environment:
      - ES_URL=elas:9200
      - PROJECT_ROOT=/home/jovyan/bowi
    working_dir: /home/jovyan/bowi

  actions:
    image: hirota/bowi
    networks:
      - bowi_default
    volumes:
      - "${GITHUB_WORKSPACE}:/workplace"
      - "${GITHUB_WORKSPACE}/bowi:/usr/local/lib/python3.8/site-packages/bowi:ro"
    environment:
      - ES_URL=localhost  # dummy
      - PROJECT_ROOT=/workplace
    working_dir: /workplace

  lsp:
    build:
      dockerfile: Dockerfile.lsp
      context: ./
    image: hirota/lsp-bowi
    volumes:
      - "${HOME}/bowi:${HOME}/bowi"
      - "${HOME}/bowi/bowi:/usr/local/lib/python3.8/site-packages/bowi:ro"
    ports:
      - 11001:11001
    command: pyls --port 11001
    stdin_open: true


networks:
  bowi_default:
    external: true
