import xml.etree.ElementTree as ET
from bowi.models import Document as Document
from pathlib import Path
from typing import Any, Iterable, Optional, TypeVar

logger: Any
T = TypeVar('T')

class NoneException(Exception): ...
class CannotSplitText(Exception): ...

def get_or_raise_exception(obj: Optional[T]) -> T: ...
def find_text_or_default(root: ET.Element, xpath: str, default: str) -> str: ...

class Converter:
    def to_document(self, fpath: Path) -> Iterable[Document]: ...

class DummyConverter(Converter): ...
