import numpy as np
from bowi.embedding.base import InvalidShape as InvalidShape, return_matrix as return_matrix, return_vector as return_vector
from typing import Any

def vec() -> np.ndarray: ...
def mat() -> np.ndarray: ...
def identity_vec_mapping(vec: Any): ...
def identity_mat_mapping(mat: Any): ...
